const Constants = {
  JSON_DATA_FETCH: "JSON_DATA_FETCH",
  SIM_DATA_FETCH: "SIM_DATA_FETCH",
  SIM_START: "SIM_START",
  SIM_STOP: "SIM_STOP",
  SIM_CLEAR_SELECTIONS: "SIM_CLEAR_SELECTIONS",
  SIM_CLEAR_RESULTS: "SIM_CLEAR_RESULTS",
  SIM_CLEAR_ALL: "SIM_CLEAR_ALL",
  SIM_SELECT_NUMBER: "SIM_SELECT_NUMBER",
  SIM_DESELECT_NUMBER: "SIM_DESELECT_NUMBER",
  SIM_SELECT_RANDOM_NUMBERS: "SIM_SELECT_RANDOM_NUMBERS"
};

export default Constants;
